services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
            - ./storage:/var/www/html/storage
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - APP_KEY=${APP_KEY}
        depends_on:
            - db
            - redis

    db:
        image: mysql:8.0
        container_name: laravel_db
        ports:
            - "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - dbdata:/var/lib/mysql

    redis:
        image: redis:7.0
        container_name: laravel_redis
        ports:
            - "6379:6379"

volumes:
    dbdata:
